on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          compliance: specification
          library-manager: update
          project-type: library
          recursive: false
          report-file: latestreport
          verbose: true          
